# Generated by Django 5.2.11 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_prediction_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('epochs_completed', models.IntegerField(default=0)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('final_val_accuracy', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=50)),
            ],
            options={
                'db_table': 'training_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]

